apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-run
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbt
            env:
            - name: POSTGRES_HOST
              value: staging-postgres
