apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: data-platform
type: Opaque
stringData:
  POSTGRES_USER: dbt_user
  POSTGRES_PASSWORD: dbt_password
  POSTGRES_DB: dbt_dev